### ISSUE TITLE
Color selectors: hue slider doesn't immediately apply changes like the saturation/brightness field does

### ISSUE THREAD

**Issue by leviport** [pop-os/libcosmic#639] opened 2024-10-15 15:38 UTC
The best example of this is in Settings > Desktop > Appearance. If I change the hue slider, changes do not apply until I click in the saturation/brightness field above the hue slider. Changing the saturation/brightness field at any time applies the change immediately. 

https://github.com/user-attachments/assets/d5eb5ae7-5e1d-42d5-8a37-44079a08bf2f

I think it would feel more intuitive if the hue slider applied changes immediately, the same way the saturation/brightness field does.

**Comment by git-f0x** [comment] 2024-10-16 00:15
I asked this a while back on Mattermost, and Michael said the following:
>That would just the widget not emitting a color picking message for slider interactions. it's probably meant to not do so on purpose so that it only changes the selection model

I agree that it would be better for the slider to also apply changes, but they would probably have to be debounced.

**Comment by CristianKerr** [comment] 2024-10-17 10:22
I have the same issue. I think its not intended behavior, because the state is inconsistent with the view. If the slider was supposed to change just internal model the field that shows the hex value wouldn't change (but it does so the full change of color is expected).

As a workaround I tried to send a message ColorPickerUpdate::AppliedColor (or ActionFinished) right after the ColorPickerUpdate::ActiveColor (which is what the slider does) and while it works for the color change now, it completely spams my recent colors when moving around the satu/brightness pane.

Also I would like to add that it would be nice if elements like recent colors would be configurable to hide, because e.g. when in popover it unnecessarily makes the popup bigger especially when the recents are not needed. Same for the field that shows the hex. Sometimes its not needed there. The buttons (save and cancel) can be ommitted by not adding their label, so maybe same approach could be taken here?

Thanks a lot! I enjoy libcosmic! :blush:

**Comment by git-f0x** [comment] 2024-11-02 01:27
This will likely be fixed by pop-os/libcosmic#674.

**Closed** 2024-11-02 02:48 UTC
Labels: bug
