### ISSUE TITLE
Libcosmic App Won't Build Because of Upstream Code

### ISSUE THREAD

**Issue by bhh32** [pop-os/libcosmic#600] opened 2024-09-06 06:39 UTC
It looks like there is a bug in the upstream code that will not let me build my COSMIC DE application that is using libcosmic. Here is the compiler error screenshot:

![libcosmic_won't_build](https://github.com/user-attachments/assets/5d33fab3-8a86-4a47-9772-5d17bdeff767)

**Comment by jackpot51** [comment] 2024-09-06 13:18
Duplicate of #596, I will resolve this soon.

**Closed by jackpot51** 2024-09-06 13:18 UTC
