### ISSUE TITLE
[Bug] LIBCOSMIC's icons code takes a long  time to run on Fedora

### ISSUE THREAD

**Issue by onlyreportingissues** [pop-os/libcosmic#756] opened 2024-12-15 13:05 UTC
[LIBCOSMIC's icons code takes a long  time to run on Fedora](https://github.com/cosmic-utils/observatory/issues/24#issuecomment-2543465919)

That's the conclusion of the dev who created this app for COSMIC: https://github.com/cosmic-utils/observatory

**Comment by Adam-Cosner** [comment] 2024-12-15 21:31
Yes, when I specifically removed the code in the app that shows process icons, the freezing immediately went away. The icon::from_name function was taking >100ms per icon for whatever reason

**Comment by Adam-Cosner** [comment] 2024-12-16 03:16
Did some more digging, it seems that cosmic::desktop::IconSource::default()'s XDG-icon is not included in the fedora build of COSMIC

**Comment by Adam-Cosner** [comment] 2024-12-16 03:33
Okay final update, it seems that the Icon code only takes a really long time when it cannot find the proper icons. @onlyreportingissues try installing cosmic-icon-theme

**Comment by onlyreportingissues** [comment] 2024-12-16 17:51
> Okay final update, it seems that the Icon code only takes a really long time when it cannot find the proper icons. @onlyreportingissues try installing cosmic-icon-theme

The icon theme is installed already, it works now though with the change you did.

**Comment by wiiznokes** [comment] 2024-12-16 18:19
Maybe it can be reopened. I seems to be the cause of this issue: https://github.com/pop-os/cosmic-settings/issues/752

**Comment by mmstick** [comment] 2024-12-16 19:48
This was already fixed in freedesktop-icons last week

**Closed by mmstick** 2024-12-16 19:48 UTC
