### ISSUE TITLE
Cosmic Store crashing X11 and GPU errors.

### ISSUE THREAD

**Issue by andym881** [pop-os/libcosmic#513] opened 2024-06-25 00:33 UTC
Model Version-Systen76 Thelio(thelio-b5)

pop_os 22.04 LTS

NVIDIA GeForce RTX 4070/PCIe/SSE2 / NVIDIA Corporation

3th Gen Intel® Core™ i7-13700K × 24 
-------------------------------------------------------------------------------------------------------------------------------------------------------------
2024-06-25T00:27:39Z WARN  wgpu_hal::gles::egl] No windowing system present. Using surfaceless platform
[2024-06-25T00:27:39Z WARN  wgpu_hal::gles::egl] No config found!
[2024-06-25T00:27:39Z WARN  wgpu_hal::gles::egl] No config found!
[2024-06-25T00:27:39Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
[2024-06-25T00:27:39Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
[2024-06-25T00:27:39Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
[2024-06-25T00:27:39Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
[2024-06-25T00:27:39Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
[2024-06-25T00:27:39Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
[2024-06-25T00:27:39Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "136",
        error_code: 136,
        request_code: 148,
        minor_code: 1,
    }
[2024-06-25T00:27:40Z ERROR iced_winit::multi_window] Error Timeout when presenting surface.
[2024-06-25T00:27:41Z ERROR iced_winit::multi_window] Error Timeout when presenting surface.
[2024-06-25T00:27:42Z ERROR iced_winit::multi_window] Error Timeout when presenting surface.
[2024-06-25T00:27:43Z ERROR iced_winit::multi_window] Error Timeout when presenting surface.
[2024-06-25T00:27:44Z ERROR iced_winit::multi_window] Error Timeout when presenting surface.
[2024-06-25T00:27:45Z ERROR iced_winit::multi_window] Error Timeout when presenting surface.
[2024-06-25T00:27:45Z WARN  iced_futures::subscription::tracker] Error sending event to subscription: TrySendError { kind: Full }
[2024-06-25T00:27:45Z WARN  iced_futures::subscription::tracker] Error sending event to subscription: TrySendError { kind: Full }
[2024-06-25T00:27:45Z WARN  iced_futures::subscription::tracker] Error sending event to subscription: TrySendError { kind: Full }
[2024-06-25T00:27:45Z WARN  iced_futures::subscription::tracker] Error sending event to subscription: TrySendError { kind: Full }
[2024-06-25T00:27:45Z WARN  iced_futures::subscription::tracker] Error sending event to subscription: TrySendError { kind: Full }
[2024-06-25T00:27:45Z WARN  iced_futures::subscription::tracker] Error sending event to subscription: TrySendError { kind: Full }
[2024-06-25T00:27:45Z WARN  iced_futures::subscription::tracker] Error sending event to subscription: TrySendError { kind: Full }
[2024-06-25T00:27:45Z WARN  iced_futures::subscription::tracker] Error sending event to subscription: TrySendError { kind: Full }
[2024-06-25T00:27:45Z WARN  iced_futures::subscription::tracker] Error sending event to subscription: TrySendError { kind: Full }
[2024-06-25T00:27:45Z WARN  iced_futures::subscription::tracker] Error sending event to subscription: TrySendError { kind: Full }
[2024-06-25T00:27:45Z WARN  iced_futures::subscription::tracker] Error sending event to subscription: TrySendError { kind: Full }
[2024-06-25T00:27:45Z WARN  iced_futures::subscription::tracker] Error sending event to subscription: TrySendError { kind: Full }
[2024-06-25T00:27:45Z WARN  iced_futures::subscription::tracker] Error sending event to subscription: TrySendError { kind: Full }
[2024-06-25T00:27:45Z WARN  iced_futures::subscription::tracker] Error sending event to subscription: TrySendError { kind: Full }
[2024-06-25T00:27:45Z WARN  iced_futures::subscription::tracker] Error sending event to subscription: TrySendError { kind: Full }
[2024-06-25T00:27:45Z WARN  iced_futures::subscription::tracker] Error sending event to subscription: TrySendError { kind: Full }
[2024-06-25T00:27:45Z WARN  iced_futures::subscription::tracker] Error sending event to subscription: TrySendError { kind: Full }
[2024-06-25T00:27:45Z WARN  iced_futures::subscription::tracker] Error sending event to subscription: TrySendError { kind: Full }
[2024-06-25T00:27:45Z WARN  iced_futures::subscription::tracker] Error sending event to subscription: TrySendError { kind: Full }
[2024-06-25T00:27:45Z WARN  iced_futures::subscription::tracker] Error sending event to subscription: TrySendError { kind: Full }
[2024-06-25T00:27:45Z WARN  iced_futures::subscription::tracker] Error sending event to subscription: TrySendError { kind: Full }
[2024-06-25T00:27:45Z WARN  iced_futures::subscription::tracker] Error sending event to subscription: TrySendError { kind: Full }
[2024-06-25T00:27:45Z WARN  iced_futures::subscription::tracker] Error sending event to subscription: TrySendError { kind: Full }
[2024-06-25T00:27:45Z WARN  iced_futures::subscription::tracker] Error sending event to subscription: TrySendError { kind: Full }
thread 'main' panicked at /build/cosmic-store-dR5whJ/cosmic-store-0.1.0~1718281780~22.04~ba3452a/vendor/winit/src/platform_impl/linux/x11/event_processor.rs:1042:30:
Failed to unfocus input context: XError { description: "136", error_code: 136, request_code: 148, minor_code: 1 }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

It works when I run "env WGPU_ADAPTER_NAME=4070 cosmic-store"

Thanks

**Comment by mmstick** [comment] 2024-07-06 20:09
Duplicate of #512

**Closed by mmstick** 2024-07-06 20:09 UTC
